//
// Generated by JTB 1.3.2
//

package org.ohmage.config.grammar.visitor;
import org.ohmage.config.grammar.syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> sentence()
    * f1 -> <EOF>
    */
   public R visit(start n);

   /**
    * f0 -> expr() sentence_prime()
    *       | "(" sentence() ")" sentence_prime()
    */
   public R visit(sentence n);

   /**
    * f0 -> ( conjunction() sentence() sentence_prime() )?
    */
   public R visit(sentence_prime n);

   /**
    * f0 -> id()
    * f1 -> condition()
    * f2 -> value()
    */
   public R visit(expr n);

   /**
    * f0 -> <TEXT>
    */
   public R visit(id n);

   /**
    * f0 -> "=="
    *       | "!="
    *       | "<"
    *       | ">"
    *       | "<="
    *       | ">="
    */
   public R visit(condition n);

   /**
    * f0 -> <TEXT>
    */
   public R visit(value n);

   /**
    * f0 -> "and"
    *       | "or"
    */
   public R visit(conjunction n);

}

