//
// Generated by JTB 1.3.2
//

package org.ohmage.config.grammar.visitor;
import org.ohmage.config.grammar.syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> sentence()
    * f1 -> <EOF>
    */
   public void visit(start n, A argu);

   /**
    * f0 -> expr() sentence_prime()
    *       | "(" sentence() ")" sentence_prime()
    */
   public void visit(sentence n, A argu);

   /**
    * f0 -> ( conjunction() sentence() sentence_prime() )?
    */
   public void visit(sentence_prime n, A argu);

   /**
    * f0 -> id()
    * f1 -> condition()
    * f2 -> value()
    */
   public void visit(expr n, A argu);

   /**
    * f0 -> <TEXT>
    */
   public void visit(id n, A argu);

   /**
    * f0 -> "=="
    *       | "!="
    *       | "<"
    *       | ">"
    *       | "<="
    *       | ">="
    */
   public void visit(condition n, A argu);

   /**
    * f0 -> <TEXT>
    */
   public void visit(value n, A argu);

   /**
    * f0 -> "and"
    *       | "or"
    */
   public void visit(conjunction n, A argu);

}

