/*******************************************************************************
 * Copyright 2012 The Regents of the University of California
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. ConditionParserConstants.java */
package org.ohmage.config.grammar.parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConditionParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int TEXT = 15;
	
	/** Lexical state. */
	int DEFAULT = 0;
	
	/** Literal token values. */
	String[] tokenImage = {
			"<EOF>",
			"\"(\"",
			"\")\"",
			"\"==\"",
			"\"!=\"",
			"\"<\"",
			"\">\"",
			"\"<=\"",
			"\">=\"",
			"\"and\"",
			"\"or\"",
			"\" \"",
			"\"\\t\"",
			"\"\\n\"",
			"\"\\r\"",
			"<TEXT>",
	};
}
