/* Generated By:JavaCC: Do not edit this line. ConditionParserConstants.java */
package org.ohmage.config.grammar.parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConditionParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int TEXT = 15;
	
	/** Lexical state. */
	int DEFAULT = 0;
	
	/** Literal token values. */
	String[] tokenImage = {
			"<EOF>",
			"\"(\"",
			"\")\"",
			"\"==\"",
			"\"!=\"",
			"\"<\"",
			"\">\"",
			"\"<=\"",
			"\">=\"",
			"\"and\"",
			"\"or\"",
			"\" \"",
			"\"\\t\"",
			"\"\\n\"",
			"\"\\r\"",
			"<TEXT>",
	};
}